# Generated by Django 4.2.11 on 2024-04-01 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_predict_prediction_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comfort', models.CharField(blank=True, help_text='Comfort level descriptor', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Comfort',
                'verbose_name_plural': 'Comforts',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='comfort',
        ),
    ]
