# Generated by Django 4.2.11 on 2024-04-14 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comfort_remove_sensor_comfort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='image',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='image',
        ),
        migrations.AddField(
            model_name='comfort',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comforts', to='app.integration'),
        ),
        migrations.AddField(
            model_name='image',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.integration'),
        ),
        migrations.AddField(
            model_name='integration',
            name='secret',
            field=models.CharField(blank=True, help_text='Secrete integrate code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='app.integration'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='app.integration'),
        ),
    ]
