# Generated by Django 3.2.25 on 2024-04-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comfort_timestamp_image_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integration',
            new_name='Integrate',
        ),
    ]
