# Generated by Django 3.2.25 on 2024-04-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_integration_integrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comfort',
            old_name='integration',
            new_name='integrate',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='integration',
            new_name='integrate',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='integration',
            new_name='integrate',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='integration',
            new_name='integrate',
        ),
    ]
